### ISSUE TITLE
Vermijd <br/> tags

### ISSUE THREAD

**Issue by ju5tu5** [FouadTaissate/the-startup-responsive-interactieve-website#5]
https://github.com/FouadTaissate/the-startup-responsive-interactieve-website/blob/ee04ee1992f70fca34157d4a09b26610b459abcb/index.html#L20

Je kunt met CSS heel makkelijk ruimte boven een alinea maken door:
```css
p {
    margin-top: 1rem; 
}
```
